version: "3.6"

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.8
  INSTALL_NODE_VERSION: 12

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - node-modules:/app/node_modules
    - ./dev.db:/tmp/dev.db

services:
  db:
    image: mysql:5.7
    ports:
      - "32001:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init_sql:/docker-entrypoint-initdb.d/:ro
  flask-dev:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    links:
      - db
    image: "sweet_cms-development"
    ports:
      - "5500-5900:5500-5900"
      - "3992:3992"
    <<: *default_volumes

  flask-prod:
    build:
      context: .
      target: production
      args:
        <<: *build_args
    links:
      - db
    image: "sweet_cms-production"
    ports:
      - "5500-5900:5500-5900"
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: 4
    <<: *default_volumes

  manage:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    entrypoint: flask
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    image: "sweet_cms-manage"
    stdin_open: true
    tty: true
    <<: *default_volumes

volumes:
  node-modules:
